### ISSUE TITLE
New more/less buttons (that don't work)

### ISSUE THREAD

**Issue by michehrlich** [michehrlich/SHUNGHAMwebsite#14]
In the promises (and maybe elsewhere?) in mobile there are "more"/"less" buttons. They should not be there (and anyway they don't work - when you click "more" the text disappears, and when you click "less" it comes back). 
![screenshot_20161207-131915](https://cloud.githubusercontent.com/assets/15867551/20967836/8d0927bc-bc81-11e6-9cf6-095a998ec484.png)

**Comment by wisniowski** [comment]
I think that's just because there's missing text that should be hidden.

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-07 13:32 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by michehrlich** [comment]
Missing text that should be hidden? I don't follow..

**Comment by wisniowski** [comment]
I think it's going to be solved during the integration process. Basically,
there's some text snippet missing. Anyways, I am going to add a little JS
tweak that would prevent the "more/less" button to appear in such cases.

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-07 13:41 GMT+01:00 Paweł Wiśniowski <pawel@wisniowski.pro>:

**Comment by michehrlich** [comment]
super thanks!

**Comment by grumpycatsaysno** [comment]
@michehrlich : I just double-checked and Paul is right. You need to to fill the other texts that appear on hover and then the more/less buttons will work properly on the Home page.

**Comment by michehrlich** [comment]
The problem isn’t that the more/less buttons don’t work properly. The problem is that they exist. They were never part of the design.

**Comment by michehrlich** [comment]
Let me clarify, a couple things:

1) This ticket is only about the promises on the home page, directly under the top banner, and not about other parts of the website.

2) the original design did include "..." which can be understood to mean something like a "more/less" button but it did not show more/less buttons.

I am not agains a more/less button. However, it is not a solution to say that we have to add more text in order to make them work. We don't add text for the sake of adding text - the text is there to communicate a message, and our goal is to make our messages as word-efficient as possible! So, if more/less buttons are there, then they have to behave according to a rule that says that if the next goes above x characters then they will appear and behave correctly, otherwise they won't even appear. 

I don't care which approach we use - no more/less buttons, or more/less buttons that work correctly -- but we can't have an approach that requires us to make text for the sake of having text. 

Thanks!

**Comment by grumpycatsaysno** [comment]
@michehrlich : I agree with you on "we can't have an approach that requires us to make text for the sake of having text.". However there is one more detail in the picture. The additional text when filling up the content of the widget, appears when hovering on each of the items as you can see on this video: http://www.screencast.com/t/9MZFo4ojr

Currently this is blank since no text is added. If we decide to remove the buttons (which is fine) we also need to rewrite the widget to remove the hover functionality. In that case we can use content blocks instead of the custom widgets. 

Please let me know your decision.

**Comment by michehrlich** [comment]
Yes, I see this. I think it would be a pity that you did all that work to create the custom widgets for this and then replace them with content blocks. Also, we might have use for them in the future. Is there a way to make the more/less button dependent on whether or not there is content present? If it's not present, the more/less doesn't appear?

**Comment by grumpycatsaysno** [comment]
@michehrlich : Yes, I can make the buttons dependable on the content. How about that hover functionality? Would you like me to also prevent it if there is no text filled?

**Comment by michehrlich** [comment]
Yes please! ☺

Thank you!

**Comment by michehrlich** [comment]
Fixed - thanks! Closing
