### ISSUE TITLE
Testimonial rotator not rotating

### ISSUE THREAD

**Issue by michehrlich** [michehrlich/SHUNGHAMwebsite#15]
See subject line

**Comment by grumpycatsaysno** [comment]
@wisniowski : This is the same in the HTMLs too. Can you please fix it?

**Comment by wisniowski** [comment]
Seems to rotate properly for me, both raw HTML and at
http://uat.shungham.com/ - on all browsers.

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-07 15:38 GMT+01:00 Veronica Milcheva <notifications@github.com>:

**Comment by wisniowski** [comment]
That's correct - I didn't add such function. It can be added, but please
let me know what should be time between each slide?

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-07 15:58 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by michehrlich** [comment]
Thanks - I would say 7 seconds

**Comment by wisniowski** [comment]
Got it.

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-07 16:20 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by grumpycatsaysno** [comment]
The rotator is rotating properly after latest deployment

**Comment by michehrlich** [comment]
Not rotating (you already know, just putting this here to keep track)

**Comment by michehrlich** [comment]
I see it's fixed now - thanks! Closing
