### ISSUE TITLE
Client Logo Rotator Speeding Up

### ISSUE THREAD

**Issue by michehrlich** [michehrlich/SHUNGHAMwebsite#17]
Seems to be getting faster and faster the more logos I put into the library where it takes the logos from...

**Comment by wisniowski** [comment]
Once you put final (or approximate) amount of logos, speed will need to be
adjusted - script allows us to define the total time of rotation, so when
you add more logos, it would require to move quicker to fit pre-defined
time. Sorry for that limitation.

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-07 17:41 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by michehrlich** [comment]
understand. in the meantime can we just increase the total time of rotation by a factor of about 50? We can fine-tune it later, but it's going to get insanely fast otherwise because we're uploading 300-400 images.

**Comment by wisniowski** [comment]
It can be done, just keep in mind overall website efficiency when adding
over 300-400 images ;)

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-07 17:53 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by michehrlich** [comment]
hmmm good to know, I was assuming it would fetch the images as it needs them. okay, maybe i'll have to reduce the number. I'll make some choices. what would you say is a good balance between showing off our famous clients and not loading down the website too much?

**Comment by michehrlich** [comment]
in terms of number of images, i mean

**Comment by wisniowski** [comment]
Actually, the script I used provides such feature, but I am not 100% sure
how it would work with auto-rotation option enabled (rarely use it). I
recommend to upload as much images as you would like to and once that's
done, we'll see how it behaves and add tweaks if necessary.

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-07 18:01 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by grumpycatsaysno** [comment]
I would like to step into with a note. By default Sitefinity stores images into the database. The more images you upload, the more you will increase the DB size and the roundtrip. I would recommend a CDN storage for Phase 2. See this article: http://docs.sitefinity.com/use-cdn-storage-for-content-libraries

**Comment by michehrlich** [comment]
ok

**Comment by michehrlich** [comment]
in the meantime how do we get the speed change live? I guess you need to send code to Veronica? Or can she just make the change herself?

**Comment by grumpycatsaysno** [comment]
Pawel is making fixes in the repository. So the same rule applies. I am going to redeploy my fixes + his on 13 Dec (next Tuesday)

**Comment by wisniowski** [comment]
Scripts.js, line #233, see "speed":
$('.gallery-a.slider > .inner').each(function () { $(this).bxSlider({
pager: false, controls: false, useCSS: false, adaptiveHeight: true, ticker:
true, speed: 100000, minSlides: 5, maxSlides: 50 }); });


---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-07 18:05 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by grumpycatsaysno** [comment]
@wisniowski : Could you please apply this change to the source code and commit it on the dev branch?

**Comment by wisniowski** [comment]
I applied it to the repo I had an access to, what else would you like me
to do?

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-07 18:14 GMT+01:00 Veronica Milcheva <notifications@github.com>:

**Comment by michehrlich** [comment]
What is minSlides and maxSlides? (just wondering if the value of 50 for maxSlides has any limiting effect on how many images we can have)

**Comment by grumpycatsaysno** [comment]
@wisniowski I don't see your change on the dev branch: https://github.com/michehrlich/SHUNGHAMwebsite/commits/dev. Could you please double-check?

**Comment by michehrlich** [comment]
The CDN suggestion is a good one. In the meantime I'll try to limit it to 100 of our most prestigious clients

**Comment by grumpycatsaysno** [comment]
@michehrlich : Luck you! Look at your problems :) You need to limit to top 100. I wish all of us such prosperity and even more!

**Comment by michehrlich** [comment]
:)

years of hard work!

**Comment by wisniowski** [comment]
maxSlides probably would need to be adjusted to, but only if it brings any
limitations.

Veronica, I am not so confident with Github to know what to do. Here's what
I got:
[image: Obraz w treści 1]

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-07 18:19 GMT+01:00 Veronica Milcheva <notifications@github.com>:

**Comment by wisniowski** [comment]
![a](https://cloud.githubusercontent.com/assets/3237848/20978871/d944fcb8-bcaa-11e6-9628-9a33deb489b1.jpg)

**Comment by grumpycatsaysno** [comment]
@wisniowski : I'll contact you on skype to prevent spam here :)

**Comment by grumpycatsaysno** [comment]
Fixed after latest deployment

**Comment by michehrlich** [comment]
Still way too fast!

**Comment by wisniowski** [comment]
I can set it, how much times slower do you thing it should scroll?

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-13 19:52 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by michehrlich** [comment]
It's a bit hard to say, I would have to guess, my best guess is 30 percent of the speed it is going right now, but apparently it is also a function (currently) of how many images are in the library, and I want to put in 100 for now, which is five times as many as are currently there, so we need to divide 30% by five again so 6%. Then it will be quite slow, until I add the rest of the images up to 100, at which point theoretically it should speed back up to the correct speed. (This is until we fix it in a future release so that we can control it in a more intelligent way).

**Comment by wisniowski** [comment]
I already made a function that counts the amount of items and multiplies
by selected time (currently it is 1000ms * 40 items = 40s to scroll entire
slider). I am not sure, but maybe Veronica would be able to put it as
CMS-related widget? Or we can set it manually each time in scripts.js (the
value 1000ms is defined there).

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-13 20:02 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by michehrlich** [comment]
Thanks - this is okay now. It's a bit jerky on mobile, but i will close this and will make a new issue for a future release for that issue. It's acceptable the way it is for the first release.

**Comment by wisniowski** [comment]
For mobile, we can set an alternative version - they won't scroll
themselves, but we'll add a prev/next buttons, so user will have ability to
scroll himself.

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-14 8:43 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by michehrlich** [comment]
Ok noted, thanks - will think about that.
