### ISSUE TITLE
Menu issues in mobile - links collapse section, animation

### ISSUE THREAD

**Issue by michehrlich** [michehrlich/SHUNGHAMwebsite#19]
- Links under sections ("Our Products" and "Who We Are") don't open the pages, they just collapse the section in the menu.

- Please no animation - everything should be instant (this is a rule for everything)

**Comment by grumpycatsaysno** [comment]
@wisniowski : This goes to you since it is the same in the HTMLs

**Comment by wisniowski** [comment]
Got it.

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-08 9:24 GMT+01:00 Veronica Milcheva <notifications@github.com>:

**Comment by grumpycatsaysno** [comment]
Fixed after latest deployment

**Comment by michehrlich** [comment]
Thanks! Closed!
