### ISSUE TITLE
Drop shadow under header in mobile 

### ISSUE THREAD

**Issue by michehrlich** [michehrlich/SHUNGHAMwebsite#20]
![screenshot_20161208-101638_ink_li](https://cloud.githubusercontent.com/assets/15867551/21004302/df7cb7d0-bd2f-11e6-900c-c7be0397ff6c.jpg)

**Comment by michehrlich** [comment]
In fact it's more just a line, not a drop shadow. (Anyway it shouldn't be there.)

**Comment by grumpycatsaysno** [comment]
@wisniowski : Could you please take care for this one?

**Comment by wisniowski** [comment]
Looks like this bug is caused by some third-party CSS, but I am going to
overwrite the buggy rule.

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-08 12:30 GMT+01:00 Veronica Milcheva <notifications@github.com>:

**Comment by michehrlich** [comment]
Fixed! Thanks! Closed.
