### ISSUE TITLE
"How We Work" section not laying out correctly

### ISSUE THREAD

**Issue by michehrlich** [michehrlich/SHUNGHAMwebsite#28]
See screenshot - correct layout is on the left, current layout is on the right
![capture](https://cloud.githubusercontent.com/assets/15867551/21079446/1187848a-bf92-11e6-9712-c139d489a0e5.PNG)

**Comment by wisniowski** [comment]
Got it (but caused by third-party CSS that I had to overwrite).

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-11 11:08 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by grumpycatsaysno** [comment]
Fixed after the latest deployment

**Comment by michehrlich** [comment]
Thanks! Closing
