### ISSUE TITLE
Question: pixel dimensions and file size for banner pictures

### ISSUE THREAD

**Issue by michehrlich** [michehrlich/SHUNGHAMwebsite#31]
Paul and/or Veronica: how should I prepare my banner photos - what are the optimal pixel dimensions and file sizes (in other worlds how big/small should I make the jpegs when exporting from Photoshop)? Thanks!

**Comment by wisniowski** [comment]
I think that something like 2000x800 would fit - it adjusts itself to the
screen automatically anyways (just make sure you like the way it adjusts on
mobile landscape view).

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-13 6:09 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by michehrlich** [comment]
Thanks!
