### ISSUE TITLE
Subheaders much too big in Privacy and Terms pages

### ISSUE THREAD

**Issue by michehrlich** [michehrlich/SHUNGHAMwebsite#32]
On left, what it  should look like; on right, what it does look like. Browser windows same size:
![image](https://cloud.githubusercontent.com/assets/15867551/21131316/4a5cd904-c10e-11e6-980f-9705fd2e8b9d.png)

**Comment by wisniowski** [comment]
Looks like CSS wasn't updated properly?

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-13 8:29 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by grumpycatsaysno** [comment]
@michehrlich : Please note that these are Content Blocks where you can edit the headers and styling of the text via the Sitefinity CMS. Please let me know if you want me to clarify this

**Comment by grumpycatsaysno** [comment]
@michehrlich : Applied better styled texts and fixed the grey background to fit the whole screen. You will see tomorrow after the deployment.

**Comment by michehrlich** [comment]
Thanks! Closing (looks good already now, for some reason :) )
