### ISSUE TITLE
White space at top of events list in mobile

### ISSUE THREAD

**Issue by michehrlich** [michehrlich/SHUNGHAMwebsite#35]
![screenshot_20161213-113842](https://cloud.githubusercontent.com/assets/15867551/21137245/33b88728-c129-11e6-8a68-fc25dc8be50a.png)

**Comment by wisniowski** [comment]
To troubleshoot this issue, I would need to be able to see "uat" version
live. Does this bug show on my raw HTML code?

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-13 11:42 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by michehrlich** [comment]
uat.shungham.com

no it is not in your original HTML file

________________________________

**Comment by wisniowski** [comment]
Got it.

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-13 11:59 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by grumpycatsaysno** [comment]
Fixed and will be deployed tomorrow.

**Comment by michehrlich** [comment]
Thanks! Closing
