### ISSUE TITLE
Make it possible to control order of Team Members on Team page

### ISSUE THREAD

**Issue by michehrlich** [michehrlich/SHUNGHAMwebsite#36]
Let order of Team Members be controlled by last publish date-and-time of each Team Member widget. The oldest should be last on the page, the newest at the top.

**Comment by grumpycatsaysno** [comment]
@michehrlich : This is exactly the way the order is working now. Try to unpublish and then publish someone and he will appear first on the list (e.g. lately published is on top).

**Comment by michehrlich** [comment]
Not working for me -- yes they appear in the correct order on the list in the back end, but of course I don't really care about that- I want to control the order in which they appear at the front end.

**Comment by grumpycatsaysno** [comment]
@michehrlich : Ok, let me test more and I will update you

**Comment by michehrlich** [comment]
Those dates are not the correct ones. I re-published everyone this afternoon. I republished myself first, then Geraint, and so on, in order of decreasing seniority, all the way down to Aliénor who is our intern. This is what it looks like in the back end list: 
![image](https://cloud.githubusercontent.com/assets/15867551/21154362/71684be0-c16e-11e6-8223-42c8ca55ceb2.png)

**Comment by grumpycatsaysno** [comment]
@michehrlich : Fixed and deployed. Please test on UAT

**Comment by michehrlich** [comment]
Thanks! Closed.
