### ISSUE TITLE
Question regarding fading gradient on banner pictures

### ISSUE THREAD

**Issue by michehrlich** [michehrlich/SHUNGHAMwebsite#37]
On some pages, there seems to be a built-in fade overlay for the banner picture (see screenshot below). It's a white gradient that gets increasingly transparent as you move down. Having a white translucent layer helps text readability but having it built into the software takes control away from the user. I would rather do this in photoshop where I have complete control, and then have the image shown in full clarity on the website. Can this be changed still in this version? Otherwise for next release. 
![image](https://cloud.githubusercontent.com/assets/15867551/21150837/b5e9fc04-c160-11e6-81ce-68508344dad3.png)

**Comment by michehrlich** [comment]
I see that I already talked about this in issue number 27. I guess it's basically the same issue. Question is whether we can do anything now...

**Comment by wisniowski** [comment]
I can remove gradient, but it will affect all the pages.

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-13 18:19 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by michehrlich** [comment]
Okay let's leave it then for now. Thanks I'll close this for now.
