### ISSUE TITLE
In Mobile, EU Calendar Policy Area selector closes each time a PA is selected

### ISSUE THREAD

**Issue by michehrlich** [michehrlich/SHUNGHAMwebsite#39]
In the mobile view it is not possible to select more than one Policy Area in EUCALENDAR without first having to re-open the selector because it closes each time you touch a Policy Area. It has to remain open so that the user can make all her choices and then close it manually.

**Comment by michehrlich** [comment]
This is due to the fact that the page reloads every time a new parameter is added. At the moment nothing can be done about this, so the only answer for now is to keep these items (sort by and policy area filter) open in mobile. Closing for now.

**Comment by grumpycatsaysno** [comment]
@michehrlich : Fixed and deployed. Please test on UAT

**Comment by michehrlich** [comment]
Still closes when selecting a Policy Area

**Comment by michehrlich** [comment]
... in mobile.

**Comment by grumpycatsaysno** [comment]
@michehrlich : I just retested on Chrome and it works. Can you please check with Incognito window?

**Comment by michehrlich** [comment]
I do all my testing in incognito now... and for me it still doesn't work...

**Comment by michehrlich** [comment]
hang on i have an idea

**Comment by michehrlich** [comment]
no... i thought that maybe it loaded a different logic if i started out on a mobile device rather than a pc, so i tested in an incognito chrome window on my android device but no it still doesn't work

**Comment by grumpycatsaysno** [comment]
Yes, I just reproduced the problem. It is my fault. Sorry about that. Fixing is on the way

**Comment by grumpycatsaysno** [comment]
@michehrlich : Fixed. Please test on UAT

**Comment by michehrlich** [comment]
What happens now is that the first time I go to EUCALENDAR (incognito mode) the menu is open when I arrive. This can't be the solution however.

**Comment by grumpycatsaysno** [comment]
@michehrlich : This is what I tried to explain during our last call. We can have either everything opened on mobile (even on the first load) or everything closed. There is no way for us to catch if this is the very first load on mobile screen. I will think of another solution for Phase 2 (maybe only leaving the section open only when a specific area is selected and closing it if All Policy Areas are selected)

**Comment by michehrlich** [comment]
What I had understood was that we were talking about the sub-drop-downs being open, but in my mind this would be acceptable because the top-level-drop-down would be closed until the user opens it. If possible, this is still the way it should be. 

But, in fact, I believe that the problem arises because the control is not behaving as expected. I understand why the page has to reload when a new filter is applied; the problem is that the filter is being applied each time a checkbox is clicked. To me, this does not seem normal. The point of checkboxes is that you click all the ones you want first, and THEN you apply the filter, by closing the drop-down.

We cannot go live with it the way it is. Hopefully we can change the behaviour of the control, even if it means getting Pawel involved again...

**Comment by michehrlich** [comment]
And in fact, I have to correct my previous comment: it would not be acceptable even if the top-level drop-down is closed on page load, because then what will happen is, say, the user wants to select three Policy Areas. He opens the top-level drop-down, scrolls to the Policy Area he wants in the filter (which will aleady be open) and selects the first one. Then the page reloads and comes back with the top-level drop-down closed again, so he has to open it again before making his second selection. This is not okay. We have to change the behaviour of the control so that it does not apply the filter until the user closes the control. 

I have one other idea but I do not know whether it is possible: we use a cookie, and we record in the cookie the last choice the user made: should the drop-down be open or closed? If he opens it, then the page always reloads with the drop-down open, until he closes it, and then the cookie says "okay, now every time a page loads, keep the control closed" (until the user opens it again).

**Comment by michehrlich** [comment]
Notes from this morning's phone call:

We are going to use the URL to determine whether or not the top-level navigation is open or closed at page load. When the url is shungham.com/eucalendar, the page loads with the top navigation closed. If the url contains further elements, the page loads with the top navigation open.

What this means in terms of user experience is that when someone first comes to eucalendar, the top nav is closed. if they open it and only choose to change the sort-by, then the page reloads and returns with top-nav closed. but if they open it and make a policy area selection, ten the page returns with top nav open.

Regarding sub-navs, these should either:
1) always return open, or
2) the possibility to close/open them should be removed.
Number 2 is preferable, if not much work. Otherwise we will go with number 1 now, and leave number 2 for a future release.

**Comment by grumpycatsaysno** [comment]
Fixed and deployed on UAT

**Comment by michehrlich** [comment]
Yes! Thank you! Closing.

**Comment by michehrlich** [comment]
Milestone completed! Great work everyone!
