### ISSUE TITLE
White space between banner and background on Terms page

### ISSUE THREAD

**Issue by michehrlich** [michehrlich/SHUNGHAMwebsite#40]
I know that you guys are aware of this issue, I'm just putting it here for the sake of completeness and keeping track. 
![image](https://cloud.githubusercontent.com/assets/15867551/21170317/6959dddc-c1c4-11e6-9f11-1c7f9fb4b8d4.png)

**Comment by wisniowski** [comment]
I will add CSS fix.

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-14 6:13 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by michehrlich** [comment]
Thanks Paul, in fact Veronica already fixed it so it's good now, I'm closing it.
