### ISSUE TITLE
Text not formatted correctly in Terms/Privacy page

### ISSUE THREAD

**Issue by michehrlich** [michehrlich/SHUNGHAMwebsite#41]
On mobile, it is centered but it should be left-aligned with natural flow on the right. On Desktop, it is aligned both left and right but it should be only left-aligned, with natural flow on the right. See screenshots - on the left of each screenshot is the correct HTML, on the right is the deployed page.
![mobile](https://cloud.githubusercontent.com/assets/15867551/21170432/6fbb3af8-c1c5-11e6-9f14-850822131a93.PNG)
![desktop](https://cloud.githubusercontent.com/assets/15867551/21170434/7342d4a6-c1c5-11e6-899c-10fced37267b.PNG)

**Comment by wisniowski** [comment]
I will fix it with CSS.

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-14 6:20 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by grumpycatsaysno** [comment]
@michehrlich : Fixed on UAT. Please check.

**Comment by michehrlich** [comment]
Yup! Thanks - closing.
