### ISSUE TITLE
Make widget body text left-aligned (future release)

### ISSUE THREAD

**Issue by michehrlich** [michehrlich/SHUNGHAMwebsite#45]
Make the body text of the following widgets/sections left-aligned in mobile:
- "Our Products" on home page
- "What Drives Us" on home page
- Testimonials on home page
- "Features" on product pages 
- "What Drives Us" on About Us page
- Bios in Team page
- Job widgets on Careers page

**Comment by wisniowski** [comment]
What Drives Us" on home page - there's a class "mobile-text-center" that
needs to be removed from this section.
"What Drives Us" on About Us page - as above

Other I can adjust via CSS.

---
Best regards,
Paul Wisniowski
<http://wisniowski.pro>
http://psdhtml.me


2016-12-14 9:33 GMT+01:00 Michel Ehrlich <notifications@github.com>:

**Comment by michehrlich** [comment]
Thanks Paul - in fact I have found that I can control this using the formatting tools available in the widget editors. I haven't tried all the widgets but those where I have, this has been available, so I'm going to assume it across the board and close this ticket. If I run into one where I can't, Ill re-open or create a new one.
