### ISSUE TITLE
Radio Button Behaviour in EU Calendar navigation

### ISSUE THREAD

**Issue by michehrlich** [michehrlich/SHUNGHAMwebsite#48]
1. When a user arrives at EU-Calendar, the sort-by radio button choice should already show the selection of "Event Date" (currently it does not show a selection). 

2. The colour of the selection indicator (currently grey) should be #c80000

**Comment by grumpycatsaysno** [comment]
Fixed and deployed. Please test on UAT

**Comment by michehrlich** [comment]
Thanks! Closed
